### ISSUE TITLE
The result of the run is incorrect

### ISSUE THREAD

**Issue by klqsebxdbsyn** [AI-Tech-Research-Lab/PyCrCNN#17]
**Describe the feature：**
When I run HE-ML.ipynb, the result is: [[0 0 0 0 0 0 0 0 0 0 0]], why is this result 0? I wonder if it's because BFV doesn't support encrypting float-type data. How can I fix this issue with the wrong output

**Comment by AlexMV12** [comment]
Hello @klqsebxdbsyn , sorry for the late response.
Yeah, it is possible that the reason is that.

Basically, in Pyfhel V2, also the _fractional encoder_ was available for BFV. It used a sort of fixed precision for encoding and encrypting floats with the BFV scheme.
We used that in the PyCrCNN paper, but then it become clear that CKKS was the "future" of HE for what concerns floats. That's why you can find the HE_ML_CKKS notebook.

If you are still curious about using BFV, you should try to install the version 2 of Pyfhel.

**Comment by klqsebxdbsyn** [comment]
Hi AlexMV12,
How to install the version 2 of Pyfhel?
Could you please tell me where I can find the installation tutorial for version 2 of Pyfhel?
